"""MQL5 bridge: generate, deploy and drive Expert Advisors on the MT5 terminal.

The web app never needs to install the MQL5 compiler - it asks the Bridge agent
(which sits next to the terminal) to:

1. write ``MQL5\\Experts\\MT5Web_<name>.mq5`` inside the terminal data folder,
2. compile it with ``metaeditor64.exe /compile:... /log:...``,
3. keep a signal file in ``MQL5\\Files\\MT5Web_<name>.txt`` that the Expert
   Advisor re-reads on every tick.

That signal file is how your Python strategy (or you, from the dashboard) drives
an EA running *inside* the terminal - no "Allow WebRequest" whitelist needed.
"""

from __future__ import annotations

import logging
import re
import time
from typing import Any

log = logging.getLogger("mt5web.mql5")

SIGNAL_FILE_PREFIX = "MT5Web_"
MQ5_ROOT_HINT = "MQL5"  # used only to build a readable fallback path


class DeployError(RuntimeError):
    pass


# --------------------------------------------------------------------------- #
# EA template
# --------------------------------------------------------------------------- #

EA_TEMPLATE = r'''//+------------------------------------------------------------------+
//|  @@FILE_NAME@@                                                   |
//|  Auto-generated by MT5 Web Console - @@CREATED@@                  |
//|  Do not edit by hand: re-deploy from the web app to update.      |
//+------------------------------------------------------------------+
#property copyright   "MT5 Web Console"
#property version     "1.00"
#property description "@@DESCRIPTION@@"

#include <Trade/Trade.mqh>

CTrade trade;

//--- generated defaults (overridable in the terminal's EA dialog)
input string  InpSignalFile      = "@@SIGNAL_FILE@@";  // signal file inside MQL5\Files
input long    InpMagic           = @@MAGIC@@;          // magic number
input string  InpSymbol          = "@@SYMBOL@@";       // symbol to trade
input int     InpTimeframe       = @@TIMEFRAME@@;      // timeframe (minutes)
input double  InpVolume          = @@VOLUME@@;         // fallback lot size
input int     InpStopLossPoints  = @@SL_POINTS@@;      // fallback SL (points)
input int     InpTakeProfitPoints= @@TP_POINTS@@;      // fallback TP (points)
input bool    InpUseFileConfig   = true;                // follow the web app's signal file
input int     InpConfigTimeoutSec= 120;                // treat config as stale after this
input bool    InpCloseOnStale    = false;               // close positions when config goes stale
input double  InpMaxSpreadPoints = 40.0;                // skip trading above this spread
input bool    InpDebugLog        = true;                // print decisions to the Experts tab

//--- runtime state (driven by the signal file)
double g_volume        = 0.0;
int    g_sl_points     = 0;
int    g_tp_points     = 0;
int    g_trail_points  = 0;
double g_max_spread    = 0.0;
double g_max_daily_loss= 0.0;
int    g_max_positions = 1;
bool   g_kill          = false;
double g_risk_percent  = 0.0;
long   g_updated       = 0;
datetime g_last_bar    = 0;
int    g_signals_seen  = 0;
int    g_orders_sent   = 0;
string g_status        = "init";

//+------------------------------------------------------------------+
bool IsMyPosition(const string symbol, const long magic)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetSymbol(i) == symbol && PositionGetInteger(POSITION_MAGIC) == magic)
         return(true);
   }
   return(false);
}

int CountMyPositions(const string symbol, const long magic)
{
   int n = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetSymbol(i) == symbol && PositionGetInteger(POSITION_MAGIC) == magic)
         n++;
   }
   return(n);
}

ulong FindTicket(const string symbol, const long magic)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetSymbol(i) == symbol && PositionGetInteger(POSITION_MAGIC) == magic)
         return((ulong)PositionGetInteger(POSITION_TICKET));
   }
   return(0);
}

void CloseAllMine(const string symbol, const long magic)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetSymbol(i) == symbol && PositionGetInteger(POSITION_MAGIC) == magic)
      {
         ulong ticket = (ulong)PositionGetInteger(POSITION_TICKET);
         if(trade.PositionClose(ticket) && InpDebugLog)
            Print("MT5Web: closed #", ticket);
      }
   }
}

double NormalizeLots(const string symbol, const double lots)
{
   double step = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   double mn   = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double mx   = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   if(step <= 0.0) step = 0.01;
   double v = MathRound(lots / step) * step;
   if(v < mn) v = mn;
   if(v > mx) v = mx;
   return(v);
}

int PriceDigits(const string symbol)
{
   return((int)SymbolInfoInteger(symbol, SYMBOL_DIGITS));
}

string FileToStringCompat(const string file_name)
{
   int h = FileOpen(file_name, FILE_READ | FILE_TXT | FILE_SHARE_READ | FILE_ANSI);
   if(h == INVALID_HANDLE)
      return("");
   string out = "";
   while(!FileIsEnding(h))
      out += FileReadString(h) + "\n";
   FileClose(h);
   return(out);
}

//+------------------------------------------------------------------+
//| parse "key=value" lines of the signal file                        |
//+------------------------------------------------------------------+
bool ReadConfig()
{
   if(!FileIsExist(InpSignalFile))
      return(false);
   int h = FileOpen(InpSignalFile, FILE_READ | FILE_TXT | FILE_SHARE_READ | FILE_ANSI);
   if(h == INVALID_HANDLE)
      return(false);
   datetime mtime = (datetime)FileGetInteger(InpSignalFile, FILE_MODIFY_DATE);
   FileClose(h);

   string lines[];
   int n = StringSplit(FileToStringCompat(InpSignalFile), '\n', lines);
   if(n <= 0)
      return(false);

   for(int i = 0; i < n; i++)
   {
      string line = lines[i];
      StringTrimRight(line);
      StringTrimLeft(line);
      int eq = StringFind(line, "=");
      if(eq <= 0) continue;
      string key = StringSubstr(line, 0, eq);
      string val = StringSubstr(line, eq + 1);
      if(key == "signal")             g_signal      = val;
      else if(key == "updated")       g_updated     = (long)StringToInteger(val);
      else if(key == "kill")          g_kill        = (val == "1");
      else if(key == "volume")        g_volume      = StringToDouble(val);
      else if(key == "sl_points")     g_sl_points   = (int)StringToInteger(val);
      else if(key == "tp_points")     g_tp_points   = (int)StringToInteger(val);
      else if(key == "trail_points")  g_trail_points= (int)StringToInteger(val);
      else if(key == "max_spread")    g_max_spread  = StringToDouble(val);
      else if(key == "max_daily_loss")g_max_daily_loss = StringToDouble(val);
      else if(key == "max_positions") g_max_positions  = (int)StringToInteger(val);
      else if(key == "risk_percent")  g_risk_percent   = StringToDouble(val);
      else if(key == "magic")         g_magic_use      = (long)StringToInteger(val);
   }
   g_config_age = (int)(TimeCurrent() - mtime);
   g_config_ok  = true;
   if(InpConfigTimeoutSec > 0 && g_config_age > InpConfigTimeoutSec)
      g_config_ok = false;
   return(true);
}

//+------------------------------------------------------------------+
//| risk-based lot size                                              |
//+------------------------------------------------------------------+
double LotsForRisk(const string symbol, const double sl_points)
{
   if(g_risk_percent <= 0.0 || sl_points <= 0.0)
      return(g_volume > 0 ? g_volume : InpVolume);
   double tick_value = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double tick_size  = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tick_value <= 0.0 || tick_size <= 0.0)
      return(g_volume > 0 ? g_volume : InpVolume);
   double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * g_risk_percent / 100.0;
   double point      = SymbolInfoDouble(symbol, SYMBOL_POINT);
   double per_lot    = (sl_points * point / tick_size) * tick_value;
   if(per_lot <= 0.0)
      return(g_volume > 0 ? g_volume : InpVolume);
   return(NormalizeLots(symbol, risk_money / per_lot));
}

//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(InpMagic);
   trade.SetDeviationInPoints(20);
   g_volume         = InpVolume;
   g_sl_points      = InpStopLossPoints;
   g_tp_points      = InpTakeProfitPoints;
   g_magic_use      = InpMagic;
   g_max_spread     = InpMaxSpreadPoints;
   PrintFormat("MT5Web EA '%s' started: symbol=%s tf=%d magic=%I64d file=%s",
                InpName, InpSymbol, InpTimeframe, InpMagic, InpSignalFile);
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED))
      Print("MT5Web: ALGO TRADING is OFF in the terminal - press the Algo Trading button");
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   PrintFormat("MT5Web EA '%s' stopped (reason %d)", InpName, reason);
}

void OnTick()
{
   string symbol = (InpSymbol == "" || InpSymbol == "CURRENT") ? _Symbol : InpSymbol;
   if(InpUseFileConfig)
      ReadConfig();

   //--- only act on a new bar (bar-close signals, no intrabar noise)
   datetime bar_time = iTime(symbol, InpTimeframe, 0);
   if(bar_time == g_last_bar)
      return;
   g_last_bar = bar_time;

   double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
   double point = SymbolInfoDouble(symbol, SYMBOL_POINT);
   int digits = (int)PriceDigits(symbol);
   double spread_points = (ask - bid) / point;
   long magic = g_magic_use > 0 ? g_magic_use : InpMagic;

   if(g_kill)
   {
      if(CountMyPositions(symbol, magic) > 0)
         CloseAllMine(symbol, magic);
      g_status = "kill switch engaged";
      return;
   }

   if(InpCloseOnStale && !g_config_ok && CountMyPositions(symbol, magic) > 0)
   {
      CloseAllMine(symbol, magic);
      g_status = "stale config - flattened";
      return;
   }

   if(g_max_spread > 0 && spread_points > g_max_spread)
   {
      g_status = StringFormat("skipped: spread %.0f > %.0f", spread_points, g_max_spread);
      return;
   }

   string action = g_signal;
   if(StringLen(action) == 0 || action == "none")
      return;
   g_signals_seen++;

   int open_now = CountMyPositions(symbol, magic);
   bool have_buy = false, have_sell = false;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetSymbol(i) != symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
      if((int)PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) have_buy = true; else have_sell = true;
   }

   double sl = 0.0, tp = 0.0;
   double ref = (action == "buy") ? ask : bid;
   if(g_sl_points > 0) sl = (action == "buy") ? ref - g_sl_points * point : ref + g_sl_points * point;
   if(g_tp_points > 0) tp = (action == "buy") ? ref + g_tp_points * point : ref - g_tp_points * point;
   sl = NormalizeDouble(sl, digits);
   tp = NormalizeDouble(tp, digits);

   if(action == "close")
   {
      if(open_now > 0) CloseAllMine(symbol, magic);
      g_status = "flat on request";
      return;
   }

   if(action == "buy" && have_buy)  { g_status = "already long"; return; }
   if(action == "sell" && have_sell){ g_status = "already short"; return; }
   if(((action == "buy" && have_sell) || (action == "sell" && have_buy)) && !InpAllowReverse)
   { g_status = "reverse disabled"; return; }
   if(open_now >= g_max_positions)
   { g_status = "max positions reached"; return; }

   double lots = LotsForRisk(symbol, g_sl_points);
   if(lots <= 0.0) lots = g_volume > 0 ? g_volume : InpVolume;
   lots = NormalizeLots(symbol, lots);

   bool ok = false;
   if(action == "buy")  ok = trade.Buy(lots, symbol, 0.0, sl, tp, InpComment);
   if(action == "sell") ok = trade.Sell(lots, symbol, 0.0, sl, tp, InpComment);
   g_orders_sent++;

   if(InpDebugLog)
      PrintFormat("MT5Web: %s %.2f %s sl=%s tp=%s -> %s", action, lots, symbol,
                  DoubleToString(sl, digits), DoubleToString(tp, digits), ok ? "sent" : "rejected");
   g_status = ok ? StringFormat("%s %.2f sent", action, lots) : "order rejected";
}

void OnTradeTransaction(const MqlTradeTransaction &trans, const MqlTradeRequest &request, const MqlTradeResult &result)
{
   if(trans.type != TRADE_TRANSACTION_DEAL_ADD) return;
   PrintFormat("MT5Web: deal %I64u on %s (%s)", trans.deal, trans.symbol, EnumToString(trans.deal_type));
}
'''


EA_INPUTS_BLOCK = '''//--- web console metadata
input string  InpName            = "@@NAME@@";          // algo name
input bool    InpAllowReverse    = @@ALLOW_REVERSE@@;   // allow flipping a position
input string  InpComment         = "@@COMMENT@@";       // order comment
string   g_signal       = "";
bool     g_config_ok    = false;
int      g_config_age   = 0;
long     g_magic_use    = 0;
double   g_daily_start  = 0.0;
'''

TIMEFRAME_MINUTES = {
    "M1": 1, "M5": 5, "M15": 15, "M30": 30,
    "H1": 60, "H4": 240, "D1": 1440, "W1": 10080,
}


def _int(value: Any, default: int = 0) -> int:
    try:
        return int(value or default)
    except (TypeError, ValueError):
        return default


def generate_ea(rec: dict, source: str = "") -> str:
    """Return the ``.mq5`` source for an algo record (bridge or user code)."""
    if source.strip():
        return source
    name = rec["name"]
    safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
    substitutions = {
        "@@FILE_NAME@@": f"{SIGNAL_FILE_PREFIX}{safe}.mq5",
        "@@CREATED@@": time.strftime("%Y-%m-%d %H:%M"),
        "@@DESCRIPTION@@": (rec.get("description") or "MT5 Web Console bridge EA").replace('"', "'")[:80],
        "@@SIGNAL_FILE@@": f"{SIGNAL_FILE_PREFIX}{safe}.txt",
        "@@MAGIC@@": _int(rec.get("magic"), 20260917),
        "@@SYMBOL@@": rec.get("symbol", "EURUSD"),
        "@@TIMEFRAME@@": TIMEFRAME_MINUTES.get(rec.get("timeframe", "M5"), 5),
        "@@VOLUME@@": f"{float(rec.get('volume') or 0.01):.2f}",
        "@@SL_POINTS@@": _int(rec.get("stop_loss_points"), 0),
        "@@TP_POINTS@@": _int(rec.get("take_profit_points"), 0),
        "@@NAME@@": safe,
        "@@ALLOW_REVERSE@@": "true" if rec.get("allow_reverse", True) else "false",
        "@@COMMENT@@": (rec.get("comment") or safe)[:24],
    }
    out = EA_TEMPLATE
    out = out.replace("//--- generated defaults", EA_INPUTS_BLOCK + "\n//--- generated defaults", 1)
    for key, value in substitutions.items():
        out = out.replace(key, str(value))
    return out


def signal_lines(
    action: str = "none",
    *,
    volume: float | None = None,
    sl_points: float | None = None,
    tp_points: float | None = None,
    trail_points: float | None = None,
    max_spread: float | None = None,
    max_daily_loss: float | None = None,
    max_positions: int | None = None,
    risk_percent: float | None = None,
    kill: bool = False,
    magic: int | None = None,
    note: str = "",
) -> str:
    rows = [
        "# MT5 Web Console signal - written automatically, do not edit",
        f"updated={int(time.time())}",
        f"signal={action if action in ('buy', 'sell', 'close') else 'none'}",
        f"kill={1 if kill else 0}",
    ]
    for key, value in (
        ("volume", volume),
        ("sl_points", sl_points),
        ("tp_points", tp_points),
        ("trail_points", trail_points),
        ("max_spread", max_spread),
        ("max_daily_loss", max_daily_loss),
        ("max_positions", max_positions),
        ("risk_percent", risk_percent),
        ("magic", magic),
    ):
        if value not in (None, ""):
            rows.append(f"{key}={value}")
    if note:
        rows.append(f"note={note[:80]}")
    return "\r\n".join(rows) + "\r\n"


def signal_payload(rec: dict, action: str | None = None) -> str:
    """Build the file content for an algo (uses its live engine state if running)."""
    from . import algo as algo_mod

    engine = algo_mod.engine(rec.get("id")) if rec.get("id") else None
    state_action = "none"
    if action:
        state_action = action
    elif engine and getattr(engine, "pending_action", None):
        state_action = engine.pending_action
    return signal_lines(
        state_action,
        volume=rec.get("volume"),
        sl_points=rec.get("stop_loss_points"),
        tp_points=rec.get("take_profit_points"),
        trail_points=rec.get("trailing_points"),
        max_spread=rec.get("max_spread_points"),
        max_daily_loss=rec.get("max_daily_loss_percent"),
        max_positions=rec.get("max_open_positions"),
        risk_percent=rec.get("risk_percent") if rec.get("volume_from_risk") else None,
        kill=bool(rec.get("kill")),
        magic=rec.get("magic"),
        note=rec.get("name"),
    )


def file_names(rec: dict) -> tuple[str, str, str]:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", rec["name"])
    base = f"{SIGNAL_FILE_PREFIX}{safe}"
    return (
        f"MQL5/Experts/{base}.mq5",
        f"MQL5/Experts/{base}.ex5",
        f"MQL5/Files/{base}.txt",
    )


def signal_file_name(rec: dict) -> str:
    """Filename *inside* MQL5\\Files (fs_write mode="filesandbox" resolves that folder itself)."""
    return file_names(rec)[2].rsplit("/", 1)[-1]


async def compile_log_text(result: dict) -> str:
    log_path = (result or {}).get("log") or ""
    if not log_path:
        return ""
    from . import broker

    try:
        conn = broker.connection()
        content = await conn.gateway.call("fs_read", path=log_path, mode="absolute")
        if isinstance(content, dict):
            return (content.get("text") or "")[:4000]
    except Exception as exc:  # noqa: BLE001
        return f"(could not read compiler log: {exc})"
    return ""


def parse_compile_log(text: str) -> dict:
    errors = len(re.findall(r": error", text or ""))
    warnings = len(re.findall(r": warning", text or ""))
    m = re.search(r"(\d+)\s*error", text or "", re.I)
    if m:
        errors = int(m.group(1))
    m2 = re.search(r"(\d+)\s*warning", text or "", re.I)
    if m2:
        warnings = int(m2.group(1))
    first_error = ""
    for line in (text or "").splitlines():
        if ": error" in line:
            first_error = line.strip()
            break
    return {"errors": errors, "warnings": warnings, "first_error": first_error, "raw": (text or "")[:3000]}


async def deploy(rec: dict, source: str = "") -> dict:
    """Write + compile the EA on the agent machine, then push an initial signal."""
    from . import broker

    if not rec.get("name"):
        raise DeployError("algo record is incomplete")
    if not broker.hub.agents:
        raise DeployError(
            "MQL5 deployment needs the Bridge agent connected (it writes into the "
            "terminal's data folder and runs MetaEditor on the Windows machine)"
        )
    conn = broker.connection(rec.get("account_id"))
    await conn.ensure_ready()
    mq5_rel, ex5_rel, signal_rel = file_names(rec)
    ea_source = generate_ea(rec, source)

    written = await conn.gateway.call("fs_write", path=mq5_rel, content=ea_source, mode="data")
    if isinstance(written, dict) and written.get("error"):
        raise DeployError(f"agent could not write {mq5_rel}: {written['error']}")
    absolute = written.get("absolute") if isinstance(written, dict) else None
    compile_target = absolute or f"{MQ5_ROOT_HINT}/{mq5_rel}"

    compile_res = await conn.gateway.call("terminal_compile", path=compile_target, mode="data")
    compile_res = compile_res if isinstance(compile_res, dict) else {"ok": bool(compile_res)}
    log_text = await compile_log_text(compile_res)
    parsed = parse_compile_log(log_text or str(compile_res.get("output", "")))
    compiled = bool(compile_res.get("ok")) and parsed["errors"] == 0

    # first signal file so the EA has something to read immediately
    await conn.gateway.call("fs_write", path=signal_file_name(rec), content=signal_payload(rec), mode="filesandbox")

    ex5_exists = compile_res.get("ex5_exists")
    if ex5_exists is None:
        try:
            seen = await conn.gateway.call("file_exists", path=ex5_rel, mode="data")
            ex5_exists = bool(isinstance(seen, dict) and seen.get("exists"))
        except Exception:  # noqa: BLE001
            ex5_exists = False

    deploy_state = {
        "compiled": compiled,
        "ex5_exists": bool(ex5_exists),
        "compiled_at": time.time() if compiled else None,
        "mq5_path": absolute or mq5_rel,
        "ex5_path": ex5_rel,
        "signal_file": signal_rel,
        "errors": parsed["errors"],
        "warnings": parsed["warnings"],
        "first_error": parsed["first_error"],
        "log": log_text[-1500:],
        "last_push": time.time(),
        "attach": {
            "how": (
                f"Open a {rec.get('symbol')} {rec.get('timeframe')} chart in MT5, drag "
                f"'{SIGNAL_FILE_PREFIX}{re.sub(r'[^A-Za-z0-9_]', '_', rec['name'])}' from Navigator "
                "-> Expert Advisors, keep 'Allow algorithmic trading' ON."
            ),
            "auto_config_ini": bool(compile_res.get("config_ini_written")),
        },
    }
    if not compiled:
        deploy_state["error"] = parsed["first_error"] or "MQL5 compilation failed"
    return {"compiled": compiled, **deploy_state, "deploy": deploy_state}


async def undeploy(rec: dict) -> dict:
    """Flatten and disable an EA: kill flag in the signal file + removal of sources."""
    from . import broker

    out = {"killed": False, "removed": False}
    try:
        conn = broker.connection(rec.get("account_id"))
        _mq5, _ex5, signal_rel = file_names(rec)
        await conn.gateway.call(
            "fs_write", path=signal_file_name(rec), content=signal_lines("close", kill=True, magic=rec.get("magic")), mode="filesandbox"
        )
        out["killed"] = True
    except Exception as exc:  # noqa: BLE001
        out["error"] = str(exc)
    return out


async def push_signal(rec: dict, action: str = "none", **fields) -> dict:
    from . import broker

    conn = broker.connection(rec.get("account_id"))
    base = {"volume": rec.get("volume"), "sl_points": rec.get("stop_loss_points"),
            "tp_points": rec.get("take_profit_points"), "trail_points": rec.get("trailing_points"),
            "max_spread": rec.get("max_spread_points"), "max_daily_loss": rec.get("max_daily_loss_percent"),
            "max_positions": rec.get("max_open_positions"), "magic": rec.get("magic"), "note": rec.get("name")}
    base.update(fields)
    fields = {k: v for k, v in base.items() if v is not None}
    content = signal_lines(action, **fields)
    res = await conn.gateway.call("fs_write", path=signal_file_name(rec), content=content, mode="filesandbox")
    return {"ok": True, "written": res, "signal": content}


def parse_signal_text(text: str) -> dict:
    out: dict[str, Any] = {}
    for line in (text or "").splitlines():
        if "=" not in line or line.strip().startswith("#"):
            continue
        key, _, value = line.partition("=")
        out[key.strip()] = value.strip()
    return out
